name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Versi JDK yang digunakan
        distribution: 'temurin'  # Pilihan distribusi JDK (temurin, zulu, dll)

    - name: Build with Maven
      run: mvn clean install

    - name: Run unit tests
      run: mvn test
